### PR TITLE
day 3 homework

### PR DESCRIPTION
**Pull request by samnevers**
_How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;_
7/10 - The Calculator stuff was fine, but I struggled with the strings. I was having a bad brain day and just wasn't switched on.

_Was there anything that you struggled with?;_
I'm still learning to process scenarios in psuedocode - completely different way of thinking, but improving with practice. That, in addition to not really knowing anything about string properties at the time was a challenge.

_Roughly how long did it take?_
3 hours

_Additional Comments:_
Ignore the really weird unreadable code in the comments - my brother decided to play code golf with my homework and I didn't get a chance to remove them before pushing.

### CODE REVIEW

**Comment by samnevers** [comment]
**DAY FOUR**

_How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;_
6 - mainly struggled with the math equations as I'm terrible at maths. 

_Was there anything that you struggled with?;_
Math, as a subject. Ha.

_Roughly how long did it take?_
3 hours

**Comment by samnevers** [comment]
**MTA**

_How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;_
4. I was actually a little freaked out given all the talk about it being super difficult, but surprisingly found it pretty manageable with no real issues. That being said it's not pretty code and maybe I stuffed up somewhere...

_Was there anything that you struggled with?;_
Tried to add actual user input, but couldn't quite work it out.

_Roughly how long did it take?_
3 hours to get it working and trying to clean it up a little. An additional 2 - 3 hours looking up forms and ways to get the user input working before giving in. I also 

_Additional Comments_
I feel like I'm slowly getting better at thinking about approach in terms of pseudocode. Planning it out really, really helped. That being said, translating the pseudocode to actual practice I feel like I still think of JS solutions in isolated parts than envisioning the bigger, cleaner/efficient code picture. Oh well, work in progress :)

**Comment by samnevers** [comment]
**DAY SIX**

_How difficult did you find this (out of 10)? 0 being no problems at all, 10 being impossible;_
3 - Brooklyn
Still working on Busy Hands (soooo time consuming) and ecardly

_Roughly how long did it take?_
1.5 - 2 hours

**Comment by cjbarnaby** [comment]
Hey Sam, 

Good work on the homework to date! And thank you for introducing me to the term 'code golf'! 

A few little suggestions and general comments below to keep in mind in future. Let me know if you have any questions.

## Formatting and Style

Generally really good, which is nice to see - this might seem like a trivial thing, but it is hugely important - indenting is good and consistent, casing is consistent, good use of whitespace to make the code readable, etc. It makes it so much easier for other developers (and yourself) to read your code, so nice work there. 

The only thing I would mention on this front is don't forget to close your statements with semi-colons (with exceptions covered in the link below). 99.9% of the time, a missing semicolon won't break anything, and even though browsers will add your missing semicolons in for you, it's a good habit to put them in where they're supposed to go - occasionally, missing semicolons can result in an unexpected outcome, will cause code linters (validators) to kick and scream, but also, a lot of developers are semicolon Nazis. [This is a really good, quick guide on using semicolons in JS](https://www.codecademy.com/blog/78) (despite the fact that it talks about semicolons being 'optional' in certain places - they're not optional, really; a statement missing a semicolon is not actually valid JS, you're just relying on the browser to put your semicolons in for you).

## Dynamic code 

In your `cashRegister` function, your explicitly adding together the values of all the keys in the cart using the keys in that object (eg `shoppingCart.hat + shoppingCart.cat`, etc). If you were to change the names of those keys, or add more key/value pairs to the cart, you would need to update the `cashRegister` function to reflect this. 

It would be preferable to use a `for` loop to go through all the key/value pairs in the object and add the values of all those keys together. This means that you can add/remove key/value pairs to/from your object, or change the names of the keys in your object, etc, without having to touch your `cashRegister` function. eg:

```js
// Instead of:
var cashRegister = function() {
  convertPrice();
  addPrices = shoppingCart.hat + shoppingCart.cat + shoppingCart.bat + shoppingCart.mat + shoppingCart.vat + shoppingCart.rat;
  return addPrices;
};
// Prefer: 
var cashRegister = function() {
  convertPrice();
  var total = 0;
  for (var prop in shoppingCart) {
    total += shoppingCart[prop]
  }
};
```
## General comments 

- **cashRegister** - I like how you had a function to convert the (`string`) prices to `number`s, and called it in your `cashRegister` function (note that since you're re-assigning the values in your `shoppingCart` object, you'll be changing that object - sometimes it might be preferable to create a copy of the object so as to preserve the original data. Depends on the situation, obviously). And, actually, while we're on that point, there are a few methods for creating a copy of an array:

```js
var arr = [ 1, 2, 3 ];
// This won't work, since it's just creating a new variable pointing at the same object in memory.
var nope = arr; 
// You can use the slice method (with no arguments) to create a copy of the original array:
var newArray = arr.slice();
// or you can create a new, empty array, and call the `concat` method, passing in the array you want to copy:
var anotherArray = [].concat(arr);
``` 
- **triangles** - Re: your question "How the hell do you work out the area of a triangle without base x height? And the obtuse too?" - check out [Heron's Formula](http://mste.illinois.edu/dildine/heron/triarea.html) 😸 .

## Bank and cash register 

Totally fine that you didn't get through the bank and cash register problems (like we said, there was a _lot_ of homework most nights this week, we don't expect people to get through everything - just have a crack at at least some of it, which you did!), but let me know if there was anything in there you wanted help with (I'm assuming you just ran out of time, which is understandable!). 

I'll send a seperate comment re: MTA.

**Comment by cjbarnaby** [comment]
Hey Sam, 

Great job on MTA! Got it working forwards, backwards, single-line trip, multi-line trip. Awesome. 

Below are a few suggestions on how you might improve your code (and why you would want to). 

These suggestions all really come down to 'DRY'ing up your code. 'DRY' is a coding mantra you'll hear a lot - it stands for "Don't Repeat Yourself". A pretty common approach is development is to just get shit working, then think about how you can DRY it up. There are a few benefits to not repeating yourself in code - firstly, provided you're not playing code golf (woo for that word!), less code is usually easier to read than more code, so it's easier for yourself and other developers to read; secondly, if you're repeating yourself, small changes to your code will need to be implemented in multiple places, which obviously takes longer and also increases the chances of errors being introduced. 

## Using functions 

The whole purpose of functions is to create reusable blocks of code. Your program right now relies on the the `startLine`, `startStation`, `endLine` and `endStation` values being 'hardcoded' - that is, you explicitly assign them as global variables in your JavaScript. This means your JavaScript can never really get inputs from a user and return a trip based on those inputs. I would start by creating a function called `planTrip` that takes four arguments. Most of my comments below will be based on that starting point:

```js
var planTrip = function(startLine, startStation, endLine, endStation) { 

};
```

Now we'll have a reusable block of code we can call from anywhere (our own JS file, if we want, or from the browser).

## Using objects

Objects can really help to DRY up code. Throughout your code, you've got conditionals that follow this pattern:

```js
if (currentLine === "N") {
  var testLine = lineNForward;
} else if (currentLine === "L") {
  var testLine = lineLForward;
} else {
  var testLine = line6Forward;
}
```

You could eliminate a lot of that by storing your line arrays in an object, and looking up a key/value pair of lines using the start or end line as a key. Eg:

```js
var lines = {
 n: [ "Times Square", "34th", "28th", "23rd", "Union Square", "8th"],
 l: [ "8th", "6th", "Union Square", "3rd", "1st" ],
 six: ["Grand Central Terminal","33rd","28th","23rd","Union Square","Astor Place" ]
}

startLine = lines[startLine];
endLine = lines[endLine];

```

## And then...

Combining the `planTrip` function and our new `lines` object, we can eliminate your `startLineRequest, `startStationRequest`, `endLineRequest`, `endStationRequest` functions, and if we keep refactoring, we'll be able to get rid of a lot of your conditionals. 

```js
var planTrip - function(startLine, startStation, endLine, endStation) {
 startLine = lines[startLine];
 endLine = lines[endLine];
}
```

## Functions Pt II

If you see that you're repeating yourself in a few spots throughout your code, consider wrapping the code in a function. Sometimes we need to do a bit of extra work - if the code is _almost_ the same, but isn't identical, we need to figure out what arguments we would need to pass into a function to make it work in all the relevant contexts. So, for example:

```js
We've also got this here:
```js
var lineNBackward = lineNForward.slice();
lineNBackward.reverse();

var lineLBackward = lineLForward.slice();
lineLBackward.reverse();

var line6Backward = line6Forward.slice();
line6Backward.reverse();
```

They're _almost_ identical. The only difference is the line. So, we could do:

```js
var reverseLine = function(line) {
 return lines[line].slice().reverse();
}
```

Then, our code for getting the reversed stations array if the `startStationIndex` is > the `endStationIndex` is much simplified:

```js
// This:
if (startStationIndex < nextStationIndex) {
  var lineDirection = testLine;
} else {
  if (currentLine === "N") {
    var lineDirection = lineNBackward;
  } else if (currentLine === "L") {
    var lineDirection = lineLBackward;
  } else {
    var lineDirection = line6Backward;
  };
};

// Can become this:
if ( startStationIndex < nextStationIndex ) {
  lineDirection = testLine.reverse(line);
}
```

## Unnecessary semicolons

These won't break your code, but you don't need semicolons after `if` statements or `for` loops.

Hope that all makes sense. Let me know if you have any questions. 

Badger.

**Comment by cjbarnaby** [comment]
#HTML & CSS 

## Brook & Lyn

Really nice work! Looks perfect, and your CSS and HTML are all perfect. 

One suggestion, notice how if you reduce the width of the browser, some of the content resizes to fit the window and some doesn't? For a `#container` div (ie, a wrapper for your page content, whatever class name or id you give it), it's pretty common to use a `max-width` rather than an explicit `width` - that way the container will never be more than 960px, but can shrink down to accommodate smaller devices/browser windows. 

## eCardly and Busy Hands 

Let me know if you want a hand with any particular aspects of these.

**Pull request merged**
