### PR TITLE
homework day 3

### PR DESCRIPTION
**Pull request by AhiShahar**
1. 2 - not too difficult but needs a lot of attention which is hard to master after 10 hrs 
2. mostly in Elpquent Javascript chapter 4 , but not uploading results. should I?
3. Eloquent Javascript :(
4. about 2 hours (not sure what time it was given? so much has happened since)

### CODE REVIEW

**Comment by AhiShahar** [comment]
Added homework from day 4:
Incomplete, didn't have time to start the bank exercise... but the rest was very clear, just took a while to do because loss of concentration cause a lot of semicolons to play hide and seek and waste my time..

probably took about 3 hours.. unfinished

Thought I was struggling with the Triangle Obtuse exercise but according to Wolf it came out just fine, please review it (functionality was good its the formula I'm uncertain of)

**Comment by AhiShahar** [comment]
Weekend project MTA:
completed it with arrays and with object, sending through the object version as it is a bit longer but much cleaner and have more options for development (adding a third and fourth and whatever line should be easier)
done the array version on the bus so about 40 minutes plus half  hour in class, but without cleaning it..
spent about 2 hours last night on this, and another half-hour to and hour trying to re-write some of it but gave up.. (wanted to implement the third line option condition but you said not to complicate things)
all in all fun project, not too challenging to complete but the challenge started when I started improving it.

**Comment by AhiShahar** [comment]
logging out a list of stations/lines

**Comment by AhiShahar** [comment]
monday week 2 homeword,
partially completed... fair bit of hours.. around 2 hours in class + almost 2 on bus and home..

**Comment by AhiShahar** [comment]
It was hard to think of a design and implement it with minimal experience... but it was a fun task and obviously not my proudest moment but understanding that the task is also dealing with the time limit and pressure pleased enough with the result.. not all the info is in yet as I've gotten a little carried away with info bubbles and ran out of data... good night. ohh and about 4 hrs..

**Comment by AhiShahar** [comment]
added the email response into the site :)

**Comment by cjbarnaby** [comment]
Hey Ahi, 

Sorry for the delay in getting this feedback to you. Should be able to turn feedback round a bit quicker now that I'm (almost) caught up on things. 

Really good work so far. You've obviously got a handle on everything. A few suggestions and comments below: 

# Week 1 Days 3 & 4
## JavaScript 

### Style and formatting

Most of the suggestions below relate to things that won't break your code, but would make it easier for yourself and other developers to read your code. There's no universally accepted style guide for JS, but all the suggestions in the [Idiomatic JS Style Guide](https://github.com/rwaldron/idiomatic.js) are pretty uncontroversial and, imho, pretty good.

- **Unnecessary semicolons** - `if` statements and `for` loops shouldn't have trailing semicolons (they generally won't break your code, but they don't belong there) - a basic rule is a closing curly bracket / brace (`}`) shouldn't be followed by a semicolon unless it is the closing bracket in an assignment statement (like `var obj = {};`). [This is a pretty good, succinct guide on when/not to include semi-colons](https://www.codecademy.com/blog/78), but I really don't agree with their suggestion that semicolons are ever 'optional' - a statement without a trailing semi-colon is not valid JS, browser's are just being kind by inserting semicolons where they _think_ you need them. Which brings me to:
- **Missing semicolons** - 99.9% of the time, a _missing_ semicolon won't actually break anything (though linters will usu. kick and scream about them, which is distracting), but it is possible. Also, some developers _really hate_ missing semi-colons. 
- **`if` statements** - JS doesn't care about how you format your code, really, but for your own sake, and for that of other developers reading your code:

```js
// this:
var drEvil = function (num) {
  if (num >= 1000000) {num = num + " dollars (pinky)"}
  else { num = num + " dollars"};
  console.log(num);
};

// is probably more readable as:
var drEvil = function (num) {
  if (num >= 1000000) {
    num = num + " dollars (pinky)"
  } else { 
    num = num + " dollars"
  };
  console.log(num);
};
```

Those are just some suggestions - not being critical! I'll post feedback re: other homework to date in seperate comments on this PR. 

Badger.

**Comment by cjbarnaby** [comment]
# MTA

Good job with this. It's a really hard problem to solve, especially after only 4 days of JS, so nice work. 

Below are a couple of comments and suggestions.

## Reversing an array

No doubt you encountered the fact that `Array.reverse()` is a mutator/destructive function - it mutates the array it was called upon, rather than returning a new array. There are a few ways to get around this. Your `reverseArr` method does it, but I shudder to think how long it would have taken to figure that out! 

```js
// Option 1: using concat - create a new, empty array, call the concat method (which concatenates the array it was called upon with the array passed in as an argument to the method) and call the reverse method on the resulting array. 

var reverseArr = function(array) {
  return [].concat(array).reverse();
}

// Option 2: using slice - slice returns a new array, and passing nothing into the slice method just returns a copy of the original array, unchanged:

var reverseArr = function(array) {
  return array.slice().reverse();
}
```

## Dynamic code 

While it's nice to be able to reduce the number of parameters your `planTrip` function requires to two, that requires changes to the data (ie, the `lines` object and the elements in the `stops`) it's using to make it work. It relies on all your stations having unique station names (which makes it a lot harder to maintain). 

## Logic 

I think there's an issue in your program's logic. If I try to go from 28th (N Line) to Union Square, it tells me to change to the 6 Line at Union Square and continue to Union Square. This is because the nested `for` loop in your `planTrip` function will ultimately end up assigning to `endLn` whatever key/value pair in the lines object it tests last (so, because it tested the 6 Line last, and it found "Union Square" in that line's array of stations, it ended up assigning `tripEnd` the array of stations on the Six line, and `endLine` the value of "6".

## For loops

Don't forget to declare the iterator you're using in your for loops. Example: 

```js
// Instead of: 
  for (i = 0 ; i < trip.length ; i += 1) {
  // etc
  }

// Do: 
  for (var i = 0; i < trip.length; i++) { 
    // etc 
  }
```

If you don't do that, JS will treat the `i` as a global variable, and re-assign 0 as that global variable's value. This can screw up other `i` variables in your code (also a real problem if two loops are running at the same time, for example). Declaring the iterator scopes the assignment to your for loop. 

```js

var i = "X";
console.log(i);
// => "X"

// Without declaring the variable - changes the value of `i` in the global scope:
var doStuff = function() {
  for ( i = 0; i < 3; i++ ) {
   console.log(i);
  }
}
doStuff();
// => 0
// => 1
// => 2
console.log(i);
// => 2

// Declaring the variable - scopes the assignment to the loop:
var i = "X"; 
var doStuff = function() {
  for ( i = 0; i < 3; i++ ) {
   console.log(i);
  }
}
doStuff();
// => 0
// => 1
// => 2
console.log(i);
// => X
```

Let me know if you have any questions!

Badger.

**Comment by cjbarnaby** [comment]
## HTML Labs 

Really nice work on Busy Hands and Brook&Lyn! A few suggestions:

## DRY CSS

Not sure if I've mentioned this acronym before but "DRY" stands for "Don't Repeat Yourself" and means pretty much what it says - "DRY" code (code where repetition is minimized) is faster to write, easier to read, easier to maintain, and reduces the chances of errors being introduced. 

If you find that you have a CSS declaration appearing in a few different rule sets, or a group of declarations that are common to a few different rule sets, think about whether you can DRY your CSS up by either:

1. Giving those elements a common class that you can select in your CSS; or
2. Selecting multiple selectors (comma separated selectors).

Eg:

```css
#fb {
  width: 60px;
  height:60px;
  float: left;
  background:url('../images/socialFf.png') center top no-repeat;
}
#in {
  width: 60px;
  height:60px;
  float: left;
  background:url('../images/socialInf.png') center top no-repeat;
}
/* etc */
```

I would either give all those elements a common class (like "social-links") or use comma separated selectors for all those rules common to all the elements. Example:

```css
/* unique styles */
#fb {
  background-image: url('../images/socialFf.png');
}

#in {
  background-image: url('../images/socialInf.png');
}

/* common class approach */

.social-links {
  width: 60px;
  height:60px;
  float: left;
  background-position: center top;
  background-repeat: no-repeat;
}

/* multiple selector approach */

#fb, #in, #ccc, #twit {
  width: 60px;
  height:60px;
  float: left;
  background-position: center top;
}
```

## `box-sizing: border-box`

With `box-sizing: border-box`, the dimensions of an element are measured inclusive of the content, padding and border but _not_ the margin. So, if you check out your `.sponsor` divs, the image in those divs goes over the right of the div's right border. This is because your image has a `width: 100%` (ie, 100% of the containing div's width), which makes it, say, 244px wide, but this _excludes_ the `margin: 3px` you have on each side. 

You want those images to be 100% of their parent _including_ the white around the edge. To achieve that, you could give the img a `border: 3px solid white` (since the `img`, including it's border, will be 100% of the width of its parent). 

## Containers

It's pretty common to wrap all our elements in a div (often given the class or ID of `container` or `wrapper` or something like that, but that's just a convention). It's a good idea to give these a `max-width: 1000px` (for example), rather than an explicit `width: 1000px`. That way, on smaller devices, or when the browser's width is reduced, the browser will fit the content into the browser's width (but, on larger devices, won't blow out to an enormous width). This is subject to the styling of other elements in your HTML, obviously. 

## `overflow: auto`

I'd use this sparingly. Generally, the default (`overflow: visible`)  will be just fine (you don't _really_ want to give users a scroll bar unless they need it view your content - you don't want them having to scroll a nav bar, or a banner, for example). On my laptop, I've got a few random scrollbars - eg, on the `.bars` div.

**Pull request merged**
