### PR TITLE
added geometry exercise

### PR DESCRIPTION
**Pull request by mariomaia77**
hi Badger,

I had  a go at the geometry tasks (wil try the other ones over the weekend). They work but if I have the feeling that I'm over using/doing var s and returns etc.. cheers

### CODE REVIEW

**Comment by mariomaia77** [comment]
MTA: 

Hi Badger, the file seems to work okay as long as you enter the right names for stations and lines. 

Looking at my Javascript, i did not use the return function anywhere, which i assume would made the coding clearer.. happy for any feedback you may have.. thanks heaps

**Comment by mariomaia77** [comment]
Added Brooklyn. Frankly, i did struggled with it especially to get the photos aligned with the text and to get it to work when you reduce the browser.

**Comment by cjbarnaby** [comment]
Hey Mario, 

Some more feedback on your homework so far! 

## MTA 

Great work on MTA - the logic looks solid, and the test trips I put in all seemed right. Must've taken an _incredibly_ long time, though, so my comments below are generally tips on writing/refactoring code to be DRY and efficient. 'DRY' is an acronomy you'll hear a lot on the dev community - it stands for "Don't Repeat Yourself". Less repetition in your code means (1) the code is easier to follow; (2) the code is easier to update; (3) less opportunities for errors to be introduced when updating the code, etc.

### DRY code using objects. 

Looking at this:

```js
var subwayLine = [ "N", "L", "6" ];
var lineN = [ "Times Square", "34th", "28th", "Union Square", "8th"];
var lineL = [ "8th", "6th", "Union Square", "3rd", "1st"];
var line6 = [ "Grand Central", "33rd", "28th", "23th", "Union Square", "Aston Place"];
```

Your `subwayLine` array is pretty much just being used as an index for the three lines. The collection of if statements and assignments like the one below are effectively just _mapping keys_ (elements in the `subwayLine` array) to _values_ (elements in the `lineN`, `lineL` and `line6` arrays):

```js
    if ( startLine === "N") {                          
      var stationStartPos = lineN.indexOf(startStation);
    } //etc 
```

The fact that we're mapping a key to value suggests that maybe an object would be a good data structure here. Storing your lines in an object, and looking up arrays of stations based on a key could reduce a lot of repetition in your code. Eg:

```js
var lines = {
  N: [ "Times Square", "34th", "28th", "Union Square", "8th"],
  L: [ "8th", "6th", "Union Square", "3rd", "1st"],
  6: [ "Grand Central", "33rd", "28th", "23th", "Union Square", "Aston Place"]
}

var startStationPos = lines[startLine].indexOf(startStation);
var lineEndPos = lines[endLine].indexOf(endStation);
```

That removed 20 lines of code just for getting the indexes of the start and end stations on their respective lines. Looking through your code for all the conditions testing whether `line === "N"`, etc, I reckon you could probably lose another 50 lines of code just by making that change. 

### Functions for re-usable code 

While it works perfectly, your program isn't really re-usable - it relies on a user being `prompt`ed to set the value of particular variables at a particular point in your code as it's being read from top to bottom by the browser. The first thing you could do is wrap everything from your prompts down into a function. Now we've got a function when can call whenever we want, whether it's getting a prompt from a user, or getting the lines and stations from somewhere else. 

I would start by creating a function called `planTrip` with four arguments:

```js
var planTrip = function(startLine, startStation, endLine, endStation) { 
 
};
```

And you could pretty much just chuck all your code (up to but excluding the prompts) in that function. Now you can call it whenever you want. 

### Functions for DRY code

If you see that you're repeating, or _almost_ repeating the same lines of code, think about whether it could go into a function. Your function will need to be able to do something slightly different depending on the context from which the function was called, or the purpose for which it was called. 

You can either deal with this by checking to see whether a global variable has a particular value within that function, and doing something different if that condition is met: 

```js
var doStuff = function() { 
  if (x === "kitten") {
    console.log("aww fluffy");
  } else {
    console.log("not fluffy!");
  }
};

var x = "kitten"; 
doStuff();
// => "aww fluffy"

var x = "lizard";
doStuff(); 
// => "not fluffy!"
```

Or we can deal with this by giving the function some arguments:

```js

var doStuff = function(animal) {
  if (animal === "kitten") {
    console.log("aww fluffy");
  } else { 
    console.log("not fluffy!");
  }
}

doStuff("kitten");
// => "aww fluffy"
doStuff("lizard"); 
// => "not fluffy!"
``` 

You could do either in this case, since you've got all the lines and stations stored as global variables, but it would be preferable to create a function with arguments, and not change/rely on variables in the global namespace. 

So, lines 120-147 is almost identical to lines 149-178. The only difference is one is looking at the startLine and one's looking at the endLine. Same thing for 150-174, 189-225 (or thereabouts), where you're getting the stations for each part of the trip. So, let's put it all in a function:

```js
var getStations = function(line, startStation, endStation) {
  var stops = [];
  var startIndex = lines[line].indexOf(startStation);
  var endEndex = lines[line].indexOf(endStation);
  if (startIndex < endIndex) {
    for (var i = startIndex; i <= endIndex; i++) {
      stops.push(lines[line][i]);
    }
  } else { 
    for (var i = endIndex; i >= startIndex; i--) {
      stops.push(lines[line][i]);
    }
  }
  return stops;
};
```

Then we can call this to get all the stations on the start and end lines:
```
// need to do a bit of work here to decide whether it's a single line or multiple trip, etc, but let's assume it's a multiline trip:

var stopsOnStartLine = getStations(startLine, startStation, "Union Square");
var stopsOnEndLine = getStations(endLine, "Union Square", endStation);

// Something like:
console.log("You will need to travel " + stopsOnStartLine.length + " stops on the " + startLine + " from " + startStation + " to Union Square, and then change at Union Square before travelling " + stopsOnEndLine.length + " stops on the " + endLine + ", through to " + endStation"
```

Note: this isn't supposed to be a complete or ideal solution, just an example of how you might start refactoring. 

Good job!

**Comment by cjbarnaby** [comment]
##Brook & Lyn

### Inherited properties

Some CSS properties are inherited from their parents. `text-align` is one of those properties - if you give an element a `text-align` value, that will be inherited by all of that element's children (unless a child element has a declaration changing that value, in which case that element (and all of _it's_ children gets given a new `text-align` property. 

So, you only needed to declare `text-align: left` on the `body`, not on the `body`, then the `h1`, then the `h4`, etc. 

If you look at the MDN reference for a CSS property (eg [text-align](https://developer.mozilla.org/en/docs/Web/CSS/text-align), and see also MDN's full [list of CSS keywords](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#Keyword_index)), you'll see whether it is `inherited`). 

### Container `<div>`

Most of the styles you've applied to the `body` in your CSS are conventionally applied to a 'container' or 'wrapper' div that goes around all (or most) of the body's content. Doesn't matter what you call this div, but convention is to give it a class called `container`. 

### Centering divs

Rather than attempting to center this content using `margin-left: 100px` (or whatever, which will be all the way to the left of the window on a large device or too far to the right on a small device), we can center any block/inline-block element (like a div) that has a `width` or `max-width` using `margin: 0 auto` (this says "set the top and bottom margins to 0, set the left and right margins to be the same (auto)).

### The images

No need to give the images a `display: inline` property, since that's the default display value for images. To get that grey border with a bit of white space inside it around the image, you could do something like:

```css
img {
  padding: 3px;
  border: 5px solid grey;
}
```

Let me know if you want a hand with anything in these labs (or with HTML/CSS generally).

**Pull request merged**
