### PR TITLE
MTA_Homework

### PR DESCRIPTION
**Pull request by rhys5690**
MTA homework

### CODE REVIEW

**Comment by rhys5690** [comment]
Donald Knuth website.

Let me know if I've uploaded it correctly.

Cheers,

Rhys

**Comment by rhys5690** [comment]
Got the cat to walk across the screen, start back at the beginning and do it again

**Comment by rhys5690** [comment]
Still can't get the cat walking back!

**Comment by cjbarnaby** [comment]
Hey Rhys, 

Sorry for the delay in getting feedback to you for week 2 homework. Some notes and suggestions below:

## MTA 

Good attempt at MTA. A few things that might have gotten you a bit further along:

### Using objects 

You've created a function for working with a single line with a hard-coded array of stops. This is definitely a good approach to a problem (starting small, getting that working, then refactoring your code to be more dynamic). 

If we look at the subway lines, what we've got is a bunch of lines, each mapped to a bunch of stations (eg, the N line has the stops "Times Square", "34th", "28th", "23rd", "Union Square" and "8th"). 

This suggests that an object might be an appropriate data structure, with the line names as the keys of the object, and the arrays of stations as the values of the object. Example:

```js
var lines = {
 N: [ "Times Square", "34th", "28th", "23rd", "Union Square", "8th" ],
 L: [ "8th", "6th", "Union Square", "3rd", "1st" ],
 6: [ "Grand Central","33rd", "28th", "23rd", "Union Square", "Astor Place" ]
}
```

Now we have all our line/station data stored in an object which a single `planTrip` function can use, provided it knows what lines we're talking about. So, let's add two more arguments to the `planTrip` function (passing in the start and end lines).

```js
var planTrip = function(stopOn, stopOff, startLine, endLine) {
}

planTrip("34th", "23rd", "L", "6");
```

That will give us the arrays of stations on both lines.

### Breaking your code into smaller functions

We're going to be doing the same kind of thing regardless of whether it's a single-line or multi-line trip. The only difference is going to be that, for a multi-line trip, the end station of the first trip will be Union Square, and the start station of the second trip will be Union Square. So we could write a function that takes a line, a start station and an end station, and returns an array of stops between the two stations. As you've noticed, the way we get the stations will be different depending on whether the index of the start station is less than or greater than the index of the end station on that line. 

```js

var getStations = function(line, startStation, endStation) {
  var stations = lines[line];
  var startIndex = stations.indexOf(startStation);
  var endIndex = stations.indexOf(endStation);
  var stops = [];
  if (startIndex < endIndex) {
   for (var i = startIndex; i <= endIndex; i++) {  
     stops.push(stations[i]);
   } 
  } else {
    for (var i = endIndex; i >= startIndex; i--) {
      stops.push(stations[i]);
    }
  }
  return stops;
}
```

Since this function `return`s an array of stops for us, we can call it multiple times in our `planTrip` function to get the stops our traveller is passing through on each line:

```js
var planTrip = function(stopOn, stopOff, startLine, endLine) {
  if (startLine === endLine) { 
    var stops = getStations(startLine, stopOn, stopOff);
    console.log( "Travelling on the " + startLine + " from " + stopOn + " through " + stops.length + "stations to " + stopOff ");
  } else {
  var startLineStops = lines[startLine];  
  var endLineStops = lines[endLine];
  var startLineStops = getStations(startLine, stopOn, "Union Square");
  var endLineStops = getStations(endLine, "Union Square", stopOff);
  // etc etc
  }
}

```

## Cat Walk

Pretty close! Here's a suggested solution for getting him to walk back and forth indefinitely (with annotations):

```js
// I'm declaring (but not immediately assigning a value to) a global variable called 'timerId'. This will be used to store the ID of the setInterval animation timers we create later on.
var timerId;

// Start off by saying that the cat is moving to the right.
var movingRight = true;

// This is the function we will call regardless of whether we want the cat to move left or right.
var catWalk = function() {

  // Get the current position of the image.
  var oldPos = parseInt(img.style.left);

  // If the cat is moving right...
  if (movingRight === true) {

    // ... and the cat has not yet reached the right hand side of the window...
    if (oldPos <= window.innerWidth - 296) {
      // Add 10px to the image's style.left property.
      newPos = oldPos + 10;
      img.style.left = newPos + "px";
    // ... otherwise, if that cat HAS reached the right hand side of the window...
    } else {
      // ... change the value of the variable storing the direction the cat's moving to false (ie, "he's no longer moving right")...
      movingRight = false;
      // ... and flip the cat horizontally...
      img.style.transform = "scaleX(-1)";
    }
  // Otherwise, if the cat is moving left (ie, movingRight === false)...
  } else {
    // ... and the cat has not yet reached the left hand side of the screen...
    if (oldPos >= 0 ) {
      // ... Take 10px away from the image's style.left property.
      newPos = oldPos - 10;
      img.style.left = newPos + "px";
    // ... otherwise, if the cat HAS reached the left hand side of the window...
    } else {
      // ... change the value of the variable storing the direction of the cat's moving to true (ie, "he's moving right now"), 
      movingRight = true;
      // ...and flip the cat horizontally
      img.style.transform = "scaleX(1)";

    }
  }
};

// Even though this is the last thing in the file, this is the first step. This will:

// 1. Start an animation that will call the catWalk function every 50ms (window.setInterval(catWalk, 50)
// 2. Store the timer ID of the animation in a variable called "timerId".
// 3. The timerId is what we will use to control (eg, stop) the animation using the clearInterval method later on. My code hasn't actually used it, but if you wanted the cat to stop walking left at a certain point (eg, when he's moving left, 500px from the left of the window), you would stop that timer/animation using window.clearInterval(timerId)
timerId = window.setInterval(catWalk, 50);
```

Timers are kind of tricky. Copy and paste this into your console.
```
var count = 10;
var logger = function() { 
  count += 10;
  console.log(count)
}

var timerId = window.setInterval(logger, 1000);
console.log(timerId);
```

The first thing you should see is "1" appearing in the console. This is the ID of the timer that was created for the setInterval that's calling the logger function every 1000ms. Type `timerId` into the console again, and you should see it. We have stored this animation/setInterval function's ID in a variable called "timerId" (we can call it whatever we like). 

The next thing you'll see is the value of count being incremented by 10 and logged out every 1000ms. This will continue happening until the setInterval is cleared using the `window.clearInterval` method. We pass the timer's id we want to clear (eg `window.clearInterval(timerId)` or `window.clearInterval(1)` etc). 

[The MDN JavaScript Timers](https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Timers) Reference (those 4 links at the top in particular) are a pretty great read.

**Comment by cjbarnaby** [comment]
## Week 4 Day 1

Literally nothing I would suggest you do differently here! Great work on this!!

**Pull request merged**
