### PR TITLE
homework week1

### PR DESCRIPTION
**Pull request by ewelina-borucka**

### CODE REVIEW

**Comment by ewelina-borucka** [comment]
Added subway

**Comment by ewelina-borucka** [comment]
added website - Grace Hopper

**Comment by cjbarnaby** [comment]
Hey Ewelina, 

Sorry it's taken me a while to get feedback to you. Great work on the homework so far! Below are some suggestions and comments on what you've done so far. 

# Week 1 

## Days 2-4 

### Formatting and style

First of all, _really_ nice style and formatting. This might seem like a minor point, but well-formatted code is really important. As Jack said, your code has two audiences - the computer interpreting your code and other developers reading your code, and the other developer is more important. Specifically, you used whitespace well to make your code readable, your indenting was appropriate and consistent, and your style was generally spot on. Really great to see so early on! 


### `if` / `else if` trickle-down conditions 

Re: the Grade Assigner - perfectly valid code there, but we can often take advantage of the fact that an `if` / `else if` / `else` statement will:
- not test any conditions after a condition has been satisfied; and, conversely, 
- only test a condition if all previous conditions have failed; 

We can often use that to simplify our conditions. So, for example:

```js
  if (score >= 60 && score <= 69) {
    console.log("For " + score + ", you got a D");
  } else if (score >= 70 && score <= 79 ) {
      console.log("For " + score + ", you got a C");
  } //etc
```

If we flipped this around and started testing conditions from >90  _down_ to < 60, our conditions could be simplified:

```js
if (score >= 90) {
  console.log("For " + score + ", you got an A");
} else if (score >= 80) {
  console.log("For " + score + ", you got a B");
}
//etc 
```

We know the second condition will only be tested if the first condition is false, and if the first condition is false, we know the score can't be >= 90.

### Random comment

I like how you determined whether to put a comma or a full-stop after each star's name in the movie database problem! 

## MTA

Nice work breaking the program down into a few re-usable functions that serve a particular purpose (though it doesn't look like your code ends up actually using the `countStops` function - I guess you would call this from your `planTrip` function - eg "You must travel " + countStops(startLine, startStation, "Union Square") + " stops through [etc etc]"). You managed to get this done is close to as few lines as is possible, really. So, good job. 

### Variable names

Try to make sure your variable names are always as descriptive and transparent as possible - eg `function fromStopToStop (x, startStop, endStop) ` - another developer would really need to read the whole function to determine what `x` actually represented. Something like `line` would probably have been better. 

### Strings to variable names

Looking at your function call: `planTrip(lineL, "1st", lineN, "34th");`, I'm guessing you ran into the issue of how to pass a string to a function, but still look up a variable (obviously, if you were to try to get input from the user via the `prompt` method, or an actual HTML UI, you would be able to pass in the _variable_ `lineL`, you would need to pass a string "lineL", and get the value stored in the variable with that name. 

There are a few ways to handle this, but in this case, the simplest is probably to put your subway lines into an object. For example:

```js
var lines = {
  L: ["8th", "6th", "Union Square", "3rd", "1st"],
  Six: ["Grand Central", "33rd", "28th", "23rd", "Union Square", "Astor Place"],
  N: ["Times Square", "34th", "28th", "23rd", "Union Square", "8th"]
};
```

Then the `planTrip` function would start by getting the array of stations for that line (the _value_ of the _key_ in your object):

```js
var planTrip( startLine, startStation, endLine, endStation ) {
  startLine = lines[startLine];
  endLine = lines[endLine];
  // etc
}
```

Then a call to the `planTrip` function could be `planTrip( "L", "6th", "N", "8th" )`, etc.

**Comment by cjbarnaby** [comment]
# Week 2

## HTML LABS

Nice work on the labs! In particular, making them generally very responsive (displaying pretty well across different device/browser sizes). 

Let me know if you want a hand on achieving any of the fancy little embellishments in any of the labs. For example, getting the white inner border in Brook&Lyn using padding:

```css
img {
  padding: 3px;
  border: 5px solid grey;
}
```

### Vendor prefixes 

I noticed that you have vendor-prefixed `box-sizing` properties in your eCardly CSS - box-sizing (and the border-box value) are part of the CSS spec now, so you don't need to worry about the vendor-prefixes. Two great websites for checking browser compatibility are [Should I Prefix?](http://shouldiprefix.com/) and [Can I Use?](http://caniuse.com/) - the latter provides great notes re: known compatibility issues. [Auto-prefixer](http://autoprefixer.github.io/) is also great - this actually adds necessary/removes unnecessary prefixes to whatever CSS you enter. 

### Container divs 

It's pretty common to wrap all our elements in a div (often given the class or ID of `container` or `wrapper` or something like that, as you have, but that's just a convention). It's a good idea to give these a `max-width: 940px` (for example), rather than an explicit `width: 940px`, as you have in eCardly. That way, on smaller devices, or when the browser's width is reduced, the browser will fit the content into the browser's width (but, on larger devices, won't blow out to an enormous width). This is subject to the styling of other elements in your HTML, obviously. 

Great work so far!

**Pull request merged**
